# Generated by Django 5.2.8 on 2026-04-08 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('industry', models.CharField(max_length=120)),
                ('website', models.URLField(blank=True)),
                ('company_size', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GraduateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_level', models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PhD', 'PhD')], max_length=30)),
                ('field_of_study', models.CharField(choices=[('Business & Finance', 'Business & Finance'), ('Computer Science', 'Computer Science'), ('Data Science & AI', 'Data Science & AI'), ('Engineering', 'Engineering'), ('Healthcare & Medicine', 'Healthcare & Medicine'), ('Natural Sciences', 'Natural Sciences'), ('Social Sciences', 'Social Sciences')], max_length=80)),
                ('graduation_year', models.PositiveIntegerField()),
                ('experience_level', models.CharField(choices=[('entry', 'Entry level'), ('mid', 'Mid level'), ('senior', 'Senior level')], default='entry', max_length=20)),
                ('skills_text', models.TextField(blank=True, help_text='Comma-separated skills')),
                ('career_goal', models.CharField(blank=True, max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graduate_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student / Graduate'), ('employer', 'Employer'), ('admin', 'Administrator')], default='student', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
