# Generated by Django 5.2.8 on 2026-04-08 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prediction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('next_steps', models.JSONField(blank=True, default=list)),
                ('report_markdown', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_report', to='prediction.employabilityassessment')),
            ],
        ),
        migrations.CreateModel(
            name='CareerPathSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('match_score', models.FloatField(default=0)),
                ('summary', models.TextField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_paths', to='prediction.employabilityassessment')),
            ],
        ),
        migrations.CreateModel(
            name='SkillRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=50)),
                ('rationale', models.TextField()),
                ('priority', models.CharField(default='Medium', max_length=20)),
                ('improvement_potential', models.FloatField(default=0)),
                ('course_name', models.CharField(blank=True, max_length=150)),
                ('course_url', models.URLField(blank=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_recommendations', to='prediction.employabilityassessment')),
            ],
        ),
    ]
