# Generated by Django 5.2.8 on 2026-04-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_dashboard', '0003_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='seen_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
